# Generated by Django 3.2.7 on 2021-09-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='twitter_zipname',
            new_name='twitter_username',
        ),
    ]
