# Generated by Django 3.2.7 on 2021-09-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_rename_twitter_zipname_user_twitter_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_credit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
